// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: inventories/delivery_return_service.proto

package inventories

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ListDeliveryReturnRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pagination *Pagination `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	BranchId   string      `protobuf:"bytes,2,opt,name=branch_id,json=branchId,proto3" json:"branch_id,omitempty"`
	DeliveryId string      `protobuf:"bytes,3,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
}

func (x *ListDeliveryReturnRequest) Reset() {
	*x = ListDeliveryReturnRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inventories_delivery_return_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDeliveryReturnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeliveryReturnRequest) ProtoMessage() {}

func (x *ListDeliveryReturnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventories_delivery_return_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeliveryReturnRequest.ProtoReflect.Descriptor instead.
func (*ListDeliveryReturnRequest) Descriptor() ([]byte, []int) {
	return file_inventories_delivery_return_service_proto_rawDescGZIP(), []int{0}
}

func (x *ListDeliveryReturnRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListDeliveryReturnRequest) GetBranchId() string {
	if x != nil {
		return x.BranchId
	}
	return ""
}

func (x *ListDeliveryReturnRequest) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

type DeliveryReturnPaginationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pagination *Pagination `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	BranchId   string      `protobuf:"bytes,2,opt,name=branch_id,json=branchId,proto3" json:"branch_id,omitempty"`
	DeliveryId string      `protobuf:"bytes,3,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	Count      uint32      `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *DeliveryReturnPaginationResponse) Reset() {
	*x = DeliveryReturnPaginationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inventories_delivery_return_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeliveryReturnPaginationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryReturnPaginationResponse) ProtoMessage() {}

func (x *DeliveryReturnPaginationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventories_delivery_return_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryReturnPaginationResponse.ProtoReflect.Descriptor instead.
func (*DeliveryReturnPaginationResponse) Descriptor() ([]byte, []int) {
	return file_inventories_delivery_return_service_proto_rawDescGZIP(), []int{1}
}

func (x *DeliveryReturnPaginationResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *DeliveryReturnPaginationResponse) GetBranchId() string {
	if x != nil {
		return x.BranchId
	}
	return ""
}

func (x *DeliveryReturnPaginationResponse) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

func (x *DeliveryReturnPaginationResponse) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ListDeliveryReturnResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pagination     *DeliveryReturnPaginationResponse `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	DeliveryReturn *DeliveryReturn                   `protobuf:"bytes,2,opt,name=DeliveryReturn,proto3" json:"DeliveryReturn,omitempty"`
}

func (x *ListDeliveryReturnResponse) Reset() {
	*x = ListDeliveryReturnResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inventories_delivery_return_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDeliveryReturnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeliveryReturnResponse) ProtoMessage() {}

func (x *ListDeliveryReturnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventories_delivery_return_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeliveryReturnResponse.ProtoReflect.Descriptor instead.
func (*ListDeliveryReturnResponse) Descriptor() ([]byte, []int) {
	return file_inventories_delivery_return_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListDeliveryReturnResponse) GetPagination() *DeliveryReturnPaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListDeliveryReturnResponse) GetDeliveryReturn() *DeliveryReturn {
	if x != nil {
		return x.DeliveryReturn
	}
	return nil
}

var File_inventories_delivery_return_service_proto protoreflect.FileDescriptor

var file_inventories_delivery_return_service_proto_rawDesc = []byte{
	0x0a, 0x29, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x2f, 0x64, 0x65,
	0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x5f, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x77, 0x69, 0x72,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x69, 0x65,
	0x73, 0x1a, 0x29, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x2f, 0x64,
	0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x5f, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x5f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x21, 0x69, 0x6e,
	0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x2f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x69,
	0x63, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x9b, 0x01, 0x0a, 0x19, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79,
	0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x40, 0x0a,
	0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x20, 0x2e, 0x77, 0x69, 0x72, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x69, 0x6e, 0x76,
	0x65, 0x6e, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x1b, 0x0a, 0x09, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b,
	0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x49, 0x64, 0x22, 0xb8, 0x01,
	0x0a, 0x20, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e,
	0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x40, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x77, 0x69, 0x72, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x2e, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x2e, 0x50, 0x61,
	0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x49,
	0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x5f, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79,
	0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0xc2, 0x01, 0x0a, 0x1a, 0x4c, 0x69, 0x73,
	0x74, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x56, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x36, 0x2e, 0x77, 0x69,
	0x72, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x69,
	0x65, 0x73, 0x2e, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x52, 0x65, 0x74, 0x75, 0x72,
	0x6e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x52, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x4c, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x52, 0x65, 0x74, 0x75, 0x72,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x77, 0x69, 0x72, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x2e, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x2e, 0x44,
	0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x52, 0x0e, 0x44,
	0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x32, 0x80, 0x03,
	0x0a, 0x15, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x56, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x12, 0x24, 0x2e, 0x77, 0x69, 0x72, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x69, 0x6e, 0x76,
	0x65, 0x6e, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x2e, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72,
	0x79, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x1a, 0x24, 0x2e, 0x77, 0x69, 0x72, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x2e, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x2e, 0x44,
	0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x22, 0x00, 0x12,
	0x56, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x24, 0x2e, 0x77, 0x69, 0x72, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x2e, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73,
	0x2e, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x1a,
	0x24, 0x2e, 0x77, 0x69, 0x72, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x69, 0x6e, 0x76, 0x65, 0x6e,
	0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x2e, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x52,
	0x65, 0x74, 0x75, 0x72, 0x6e, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x04, 0x56, 0x69, 0x65, 0x77, 0x12,
	0x18, 0x2e, 0x77, 0x69, 0x72, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x69, 0x6e, 0x76, 0x65, 0x6e,
	0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x2e, 0x49, 0x64, 0x1a, 0x24, 0x2e, 0x77, 0x69, 0x72, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x2e, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73,
	0x2e, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x22,
	0x00, 0x12, 0x6d, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2f, 0x2e, 0x77, 0x69, 0x72, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x2e, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x52, 0x65, 0x74,
	0x75, 0x72, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x30, 0x2e, 0x77, 0x69, 0x72,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x69, 0x65,
	0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x52, 0x65,
	0x74, 0x75, 0x72, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01,
	0x42, 0x47, 0x0a, 0x27, 0x63, 0x6f, 0x6d, 0x2e, 0x77, 0x69, 0x72, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x2e, 0x65, 0x72, 0x70, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x50, 0x01, 0x5a, 0x1a, 0x70,
	0x62, 0x2f, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x3b, 0x69, 0x6e,
	0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_inventories_delivery_return_service_proto_rawDescOnce sync.Once
	file_inventories_delivery_return_service_proto_rawDescData = file_inventories_delivery_return_service_proto_rawDesc
)

func file_inventories_delivery_return_service_proto_rawDescGZIP() []byte {
	file_inventories_delivery_return_service_proto_rawDescOnce.Do(func() {
		file_inventories_delivery_return_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_inventories_delivery_return_service_proto_rawDescData)
	})
	return file_inventories_delivery_return_service_proto_rawDescData
}

var file_inventories_delivery_return_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_inventories_delivery_return_service_proto_goTypes = []interface{}{
	(*ListDeliveryReturnRequest)(nil),        // 0: wiradata.inventories.ListDeliveryReturnRequest
	(*DeliveryReturnPaginationResponse)(nil), // 1: wiradata.inventories.DeliveryReturnPaginationResponse
	(*ListDeliveryReturnResponse)(nil),       // 2: wiradata.inventories.ListDeliveryReturnResponse
	(*Pagination)(nil),                       // 3: wiradata.inventories.Pagination
	(*DeliveryReturn)(nil),                   // 4: wiradata.inventories.DeliveryReturn
	(*Id)(nil),                               // 5: wiradata.inventories.Id
}
var file_inventories_delivery_return_service_proto_depIdxs = []int32{
	3, // 0: wiradata.inventories.ListDeliveryReturnRequest.pagination:type_name -> wiradata.inventories.Pagination
	3, // 1: wiradata.inventories.DeliveryReturnPaginationResponse.pagination:type_name -> wiradata.inventories.Pagination
	1, // 2: wiradata.inventories.ListDeliveryReturnResponse.pagination:type_name -> wiradata.inventories.DeliveryReturnPaginationResponse
	4, // 3: wiradata.inventories.ListDeliveryReturnResponse.DeliveryReturn:type_name -> wiradata.inventories.DeliveryReturn
	4, // 4: wiradata.inventories.DeliveryReturnService.Create:input_type -> wiradata.inventories.DeliveryReturn
	4, // 5: wiradata.inventories.DeliveryReturnService.Update:input_type -> wiradata.inventories.DeliveryReturn
	5, // 6: wiradata.inventories.DeliveryReturnService.View:input_type -> wiradata.inventories.Id
	0, // 7: wiradata.inventories.DeliveryReturnService.List:input_type -> wiradata.inventories.ListDeliveryReturnRequest
	4, // 8: wiradata.inventories.DeliveryReturnService.Create:output_type -> wiradata.inventories.DeliveryReturn
	4, // 9: wiradata.inventories.DeliveryReturnService.Update:output_type -> wiradata.inventories.DeliveryReturn
	4, // 10: wiradata.inventories.DeliveryReturnService.View:output_type -> wiradata.inventories.DeliveryReturn
	2, // 11: wiradata.inventories.DeliveryReturnService.List:output_type -> wiradata.inventories.ListDeliveryReturnResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_inventories_delivery_return_service_proto_init() }
func file_inventories_delivery_return_service_proto_init() {
	if File_inventories_delivery_return_service_proto != nil {
		return
	}
	file_inventories_delivery_return_message_proto_init()
	file_inventories_generic_message_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_inventories_delivery_return_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDeliveryReturnRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inventories_delivery_return_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeliveryReturnPaginationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inventories_delivery_return_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDeliveryReturnResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_inventories_delivery_return_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inventories_delivery_return_service_proto_goTypes,
		DependencyIndexes: file_inventories_delivery_return_service_proto_depIdxs,
		MessageInfos:      file_inventories_delivery_return_service_proto_msgTypes,
	}.Build()
	File_inventories_delivery_return_service_proto = out.File
	file_inventories_delivery_return_service_proto_rawDesc = nil
	file_inventories_delivery_return_service_proto_goTypes = nil
	file_inventories_delivery_return_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DeliveryReturnServiceClient is the client API for DeliveryReturnService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DeliveryReturnServiceClient interface {
	Create(ctx context.Context, in *DeliveryReturn, opts ...grpc.CallOption) (*DeliveryReturn, error)
	Update(ctx context.Context, in *DeliveryReturn, opts ...grpc.CallOption) (*DeliveryReturn, error)
	View(ctx context.Context, in *Id, opts ...grpc.CallOption) (*DeliveryReturn, error)
	List(ctx context.Context, in *ListDeliveryReturnRequest, opts ...grpc.CallOption) (DeliveryReturnService_ListClient, error)
}

type deliveryReturnServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeliveryReturnServiceClient(cc grpc.ClientConnInterface) DeliveryReturnServiceClient {
	return &deliveryReturnServiceClient{cc}
}

func (c *deliveryReturnServiceClient) Create(ctx context.Context, in *DeliveryReturn, opts ...grpc.CallOption) (*DeliveryReturn, error) {
	out := new(DeliveryReturn)
	err := c.cc.Invoke(ctx, "/wiradata.inventories.DeliveryReturnService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryReturnServiceClient) Update(ctx context.Context, in *DeliveryReturn, opts ...grpc.CallOption) (*DeliveryReturn, error) {
	out := new(DeliveryReturn)
	err := c.cc.Invoke(ctx, "/wiradata.inventories.DeliveryReturnService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryReturnServiceClient) View(ctx context.Context, in *Id, opts ...grpc.CallOption) (*DeliveryReturn, error) {
	out := new(DeliveryReturn)
	err := c.cc.Invoke(ctx, "/wiradata.inventories.DeliveryReturnService/View", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryReturnServiceClient) List(ctx context.Context, in *ListDeliveryReturnRequest, opts ...grpc.CallOption) (DeliveryReturnService_ListClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DeliveryReturnService_serviceDesc.Streams[0], "/wiradata.inventories.DeliveryReturnService/List", opts...)
	if err != nil {
		return nil, err
	}
	x := &deliveryReturnServiceListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DeliveryReturnService_ListClient interface {
	Recv() (*ListDeliveryReturnResponse, error)
	grpc.ClientStream
}

type deliveryReturnServiceListClient struct {
	grpc.ClientStream
}

func (x *deliveryReturnServiceListClient) Recv() (*ListDeliveryReturnResponse, error) {
	m := new(ListDeliveryReturnResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DeliveryReturnServiceServer is the server API for DeliveryReturnService service.
type DeliveryReturnServiceServer interface {
	Create(context.Context, *DeliveryReturn) (*DeliveryReturn, error)
	Update(context.Context, *DeliveryReturn) (*DeliveryReturn, error)
	View(context.Context, *Id) (*DeliveryReturn, error)
	List(*ListDeliveryReturnRequest, DeliveryReturnService_ListServer) error
}

// UnimplementedDeliveryReturnServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDeliveryReturnServiceServer struct {
}

func (*UnimplementedDeliveryReturnServiceServer) Create(context.Context, *DeliveryReturn) (*DeliveryReturn, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedDeliveryReturnServiceServer) Update(context.Context, *DeliveryReturn) (*DeliveryReturn, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedDeliveryReturnServiceServer) View(context.Context, *Id) (*DeliveryReturn, error) {
	return nil, status.Errorf(codes.Unimplemented, "method View not implemented")
}
func (*UnimplementedDeliveryReturnServiceServer) List(*ListDeliveryReturnRequest, DeliveryReturnService_ListServer) error {
	return status.Errorf(codes.Unimplemented, "method List not implemented")
}

func RegisterDeliveryReturnServiceServer(s *grpc.Server, srv DeliveryReturnServiceServer) {
	s.RegisterService(&_DeliveryReturnService_serviceDesc, srv)
}

func _DeliveryReturnService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeliveryReturn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryReturnServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wiradata.inventories.DeliveryReturnService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryReturnServiceServer).Create(ctx, req.(*DeliveryReturn))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryReturnService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeliveryReturn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryReturnServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wiradata.inventories.DeliveryReturnService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryReturnServiceServer).Update(ctx, req.(*DeliveryReturn))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryReturnService_View_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryReturnServiceServer).View(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wiradata.inventories.DeliveryReturnService/View",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryReturnServiceServer).View(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryReturnService_List_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListDeliveryReturnRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DeliveryReturnServiceServer).List(m, &deliveryReturnServiceListServer{stream})
}

type DeliveryReturnService_ListServer interface {
	Send(*ListDeliveryReturnResponse) error
	grpc.ServerStream
}

type deliveryReturnServiceListServer struct {
	grpc.ServerStream
}

func (x *deliveryReturnServiceListServer) Send(m *ListDeliveryReturnResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _DeliveryReturnService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "wiradata.inventories.DeliveryReturnService",
	HandlerType: (*DeliveryReturnServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _DeliveryReturnService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _DeliveryReturnService_Update_Handler,
		},
		{
			MethodName: "View",
			Handler:    _DeliveryReturnService_View_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "List",
			Handler:       _DeliveryReturnService_List_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "inventories/delivery_return_service.proto",
}
