// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: inventories/receive_service.proto

package inventories

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ListReceiveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pagination *Pagination `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	BranchId   string      `protobuf:"bytes,2,opt,name=branch_id,json=branchId,proto3" json:"branch_id,omitempty"`
	PurchaseId string      `protobuf:"bytes,3,opt,name=purchase_id,json=purchaseId,proto3" json:"purchase_id,omitempty"`
}

func (x *ListReceiveRequest) Reset() {
	*x = ListReceiveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inventories_receive_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListReceiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReceiveRequest) ProtoMessage() {}

func (x *ListReceiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventories_receive_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReceiveRequest.ProtoReflect.Descriptor instead.
func (*ListReceiveRequest) Descriptor() ([]byte, []int) {
	return file_inventories_receive_service_proto_rawDescGZIP(), []int{0}
}

func (x *ListReceiveRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListReceiveRequest) GetBranchId() string {
	if x != nil {
		return x.BranchId
	}
	return ""
}

func (x *ListReceiveRequest) GetPurchaseId() string {
	if x != nil {
		return x.PurchaseId
	}
	return ""
}

type ReceivePaginationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pagination *Pagination `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	BranchId   string      `protobuf:"bytes,2,opt,name=branch_id,json=branchId,proto3" json:"branch_id,omitempty"`
	PurchaseId string      `protobuf:"bytes,3,opt,name=purchase_id,json=purchaseId,proto3" json:"purchase_id,omitempty"`
	Count      uint32      `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *ReceivePaginationResponse) Reset() {
	*x = ReceivePaginationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inventories_receive_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReceivePaginationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceivePaginationResponse) ProtoMessage() {}

func (x *ReceivePaginationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventories_receive_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceivePaginationResponse.ProtoReflect.Descriptor instead.
func (*ReceivePaginationResponse) Descriptor() ([]byte, []int) {
	return file_inventories_receive_service_proto_rawDescGZIP(), []int{1}
}

func (x *ReceivePaginationResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ReceivePaginationResponse) GetBranchId() string {
	if x != nil {
		return x.BranchId
	}
	return ""
}

func (x *ReceivePaginationResponse) GetPurchaseId() string {
	if x != nil {
		return x.PurchaseId
	}
	return ""
}

func (x *ReceivePaginationResponse) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ListReceiveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pagination *ReceivePaginationResponse `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Receive    *Receive                   `protobuf:"bytes,2,opt,name=Receive,proto3" json:"Receive,omitempty"`
}

func (x *ListReceiveResponse) Reset() {
	*x = ListReceiveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inventories_receive_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListReceiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReceiveResponse) ProtoMessage() {}

func (x *ListReceiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventories_receive_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReceiveResponse.ProtoReflect.Descriptor instead.
func (*ListReceiveResponse) Descriptor() ([]byte, []int) {
	return file_inventories_receive_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListReceiveResponse) GetPagination() *ReceivePaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListReceiveResponse) GetReceive() *Receive {
	if x != nil {
		return x.Receive
	}
	return nil
}

var File_inventories_receive_service_proto protoreflect.FileDescriptor

var file_inventories_receive_service_proto_rawDesc = []byte{
	0x0a, 0x21, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x2f, 0x72, 0x65,
	0x63, 0x65, 0x69, 0x76, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x14, 0x77, 0x69, 0x72, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x69, 0x6e,
	0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x1a, 0x21, 0x69, 0x6e, 0x76, 0x65, 0x6e,
	0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x2f, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x5f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x21, 0x69, 0x6e,
	0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x2f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x69,
	0x63, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x94, 0x01, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x40, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x77, 0x69, 0x72,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x69, 0x65,
	0x73, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x70, 0x61,
	0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x72, 0x61, 0x6e,
	0x63, 0x68, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x72, 0x61,
	0x6e, 0x63, 0x68, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x75, 0x72, 0x63,
	0x68, 0x61, 0x73, 0x65, 0x49, 0x64, 0x22, 0xb1, 0x01, 0x0a, 0x19, 0x52, 0x65, 0x63, 0x65, 0x69,
	0x76, 0x65, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x77, 0x69, 0x72, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x2e, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x2e,
	0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x70, 0x61, 0x67, 0x69,
	0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x72, 0x61, 0x6e, 0x63,
	0x68, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x75, 0x72, 0x63, 0x68, 0x61,
	0x73, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x9f, 0x01, 0x0a, 0x13, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x4f, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x77, 0x69, 0x72, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x2e, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x2e, 0x52, 0x65,
	0x63, 0x65, 0x69, 0x76, 0x65, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x37, 0x0a, 0x07, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x77, 0x69, 0x72, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e,
	0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x52, 0x07, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x32, 0xc8, 0x02, 0x0a,
	0x0e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x48, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x1d, 0x2e, 0x77, 0x69, 0x72, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x2e, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73,
	0x2e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x1a, 0x1d, 0x2e, 0x77, 0x69, 0x72, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x2e, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x2e,
	0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x06, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x12, 0x1d, 0x2e, 0x77, 0x69, 0x72, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x69,
	0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x63, 0x65, 0x69,
	0x76, 0x65, 0x1a, 0x1d, 0x2e, 0x77, 0x69, 0x72, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x69, 0x6e,
	0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76,
	0x65, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x04, 0x56, 0x69, 0x65, 0x77, 0x12, 0x18, 0x2e, 0x77, 0x69,
	0x72, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x69,
	0x65, 0x73, 0x2e, 0x49, 0x64, 0x1a, 0x1d, 0x2e, 0x77, 0x69, 0x72, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x2e, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x22, 0x00, 0x12, 0x5f, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x28,
	0x2e, 0x77, 0x69, 0x72, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74,
	0x6f, 0x72, 0x69, 0x65, 0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x77, 0x69, 0x72, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x2e, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x1c, 0x5a, 0x1a, 0x70, 0x62, 0x2f, 0x69, 0x6e,
	0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x3b, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74,
	0x6f, 0x72, 0x69, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_inventories_receive_service_proto_rawDescOnce sync.Once
	file_inventories_receive_service_proto_rawDescData = file_inventories_receive_service_proto_rawDesc
)

func file_inventories_receive_service_proto_rawDescGZIP() []byte {
	file_inventories_receive_service_proto_rawDescOnce.Do(func() {
		file_inventories_receive_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_inventories_receive_service_proto_rawDescData)
	})
	return file_inventories_receive_service_proto_rawDescData
}

var file_inventories_receive_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_inventories_receive_service_proto_goTypes = []interface{}{
	(*ListReceiveRequest)(nil),        // 0: wiradata.inventories.ListReceiveRequest
	(*ReceivePaginationResponse)(nil), // 1: wiradata.inventories.ReceivePaginationResponse
	(*ListReceiveResponse)(nil),       // 2: wiradata.inventories.ListReceiveResponse
	(*Pagination)(nil),                // 3: wiradata.inventories.Pagination
	(*Receive)(nil),                   // 4: wiradata.inventories.Receive
	(*Id)(nil),                        // 5: wiradata.inventories.Id
}
var file_inventories_receive_service_proto_depIdxs = []int32{
	3, // 0: wiradata.inventories.ListReceiveRequest.pagination:type_name -> wiradata.inventories.Pagination
	3, // 1: wiradata.inventories.ReceivePaginationResponse.pagination:type_name -> wiradata.inventories.Pagination
	1, // 2: wiradata.inventories.ListReceiveResponse.pagination:type_name -> wiradata.inventories.ReceivePaginationResponse
	4, // 3: wiradata.inventories.ListReceiveResponse.Receive:type_name -> wiradata.inventories.Receive
	4, // 4: wiradata.inventories.ReceiveService.Create:input_type -> wiradata.inventories.Receive
	4, // 5: wiradata.inventories.ReceiveService.Update:input_type -> wiradata.inventories.Receive
	5, // 6: wiradata.inventories.ReceiveService.View:input_type -> wiradata.inventories.Id
	0, // 7: wiradata.inventories.ReceiveService.List:input_type -> wiradata.inventories.ListReceiveRequest
	4, // 8: wiradata.inventories.ReceiveService.Create:output_type -> wiradata.inventories.Receive
	4, // 9: wiradata.inventories.ReceiveService.Update:output_type -> wiradata.inventories.Receive
	4, // 10: wiradata.inventories.ReceiveService.View:output_type -> wiradata.inventories.Receive
	2, // 11: wiradata.inventories.ReceiveService.List:output_type -> wiradata.inventories.ListReceiveResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_inventories_receive_service_proto_init() }
func file_inventories_receive_service_proto_init() {
	if File_inventories_receive_service_proto != nil {
		return
	}
	file_inventories_receive_message_proto_init()
	file_inventories_generic_message_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_inventories_receive_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListReceiveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inventories_receive_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReceivePaginationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inventories_receive_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListReceiveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_inventories_receive_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inventories_receive_service_proto_goTypes,
		DependencyIndexes: file_inventories_receive_service_proto_depIdxs,
		MessageInfos:      file_inventories_receive_service_proto_msgTypes,
	}.Build()
	File_inventories_receive_service_proto = out.File
	file_inventories_receive_service_proto_rawDesc = nil
	file_inventories_receive_service_proto_goTypes = nil
	file_inventories_receive_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ReceiveServiceClient is the client API for ReceiveService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReceiveServiceClient interface {
	Create(ctx context.Context, in *Receive, opts ...grpc.CallOption) (*Receive, error)
	Update(ctx context.Context, in *Receive, opts ...grpc.CallOption) (*Receive, error)
	View(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Receive, error)
	List(ctx context.Context, in *ListReceiveRequest, opts ...grpc.CallOption) (ReceiveService_ListClient, error)
}

type receiveServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReceiveServiceClient(cc grpc.ClientConnInterface) ReceiveServiceClient {
	return &receiveServiceClient{cc}
}

func (c *receiveServiceClient) Create(ctx context.Context, in *Receive, opts ...grpc.CallOption) (*Receive, error) {
	out := new(Receive)
	err := c.cc.Invoke(ctx, "/wiradata.inventories.ReceiveService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *receiveServiceClient) Update(ctx context.Context, in *Receive, opts ...grpc.CallOption) (*Receive, error) {
	out := new(Receive)
	err := c.cc.Invoke(ctx, "/wiradata.inventories.ReceiveService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *receiveServiceClient) View(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Receive, error) {
	out := new(Receive)
	err := c.cc.Invoke(ctx, "/wiradata.inventories.ReceiveService/View", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *receiveServiceClient) List(ctx context.Context, in *ListReceiveRequest, opts ...grpc.CallOption) (ReceiveService_ListClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ReceiveService_serviceDesc.Streams[0], "/wiradata.inventories.ReceiveService/List", opts...)
	if err != nil {
		return nil, err
	}
	x := &receiveServiceListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ReceiveService_ListClient interface {
	Recv() (*ListReceiveResponse, error)
	grpc.ClientStream
}

type receiveServiceListClient struct {
	grpc.ClientStream
}

func (x *receiveServiceListClient) Recv() (*ListReceiveResponse, error) {
	m := new(ListReceiveResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ReceiveServiceServer is the server API for ReceiveService service.
type ReceiveServiceServer interface {
	Create(context.Context, *Receive) (*Receive, error)
	Update(context.Context, *Receive) (*Receive, error)
	View(context.Context, *Id) (*Receive, error)
	List(*ListReceiveRequest, ReceiveService_ListServer) error
}

// UnimplementedReceiveServiceServer can be embedded to have forward compatible implementations.
type UnimplementedReceiveServiceServer struct {
}

func (*UnimplementedReceiveServiceServer) Create(context.Context, *Receive) (*Receive, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedReceiveServiceServer) Update(context.Context, *Receive) (*Receive, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedReceiveServiceServer) View(context.Context, *Id) (*Receive, error) {
	return nil, status.Errorf(codes.Unimplemented, "method View not implemented")
}
func (*UnimplementedReceiveServiceServer) List(*ListReceiveRequest, ReceiveService_ListServer) error {
	return status.Errorf(codes.Unimplemented, "method List not implemented")
}

func RegisterReceiveServiceServer(s *grpc.Server, srv ReceiveServiceServer) {
	s.RegisterService(&_ReceiveService_serviceDesc, srv)
}

func _ReceiveService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Receive)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReceiveServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wiradata.inventories.ReceiveService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReceiveServiceServer).Create(ctx, req.(*Receive))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReceiveService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Receive)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReceiveServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wiradata.inventories.ReceiveService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReceiveServiceServer).Update(ctx, req.(*Receive))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReceiveService_View_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReceiveServiceServer).View(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wiradata.inventories.ReceiveService/View",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReceiveServiceServer).View(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReceiveService_List_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListReceiveRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ReceiveServiceServer).List(m, &receiveServiceListServer{stream})
}

type ReceiveService_ListServer interface {
	Send(*ListReceiveResponse) error
	grpc.ServerStream
}

type receiveServiceListServer struct {
	grpc.ServerStream
}

func (x *receiveServiceListServer) Send(m *ListReceiveResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _ReceiveService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "wiradata.inventories.ReceiveService",
	HandlerType: (*ReceiveServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ReceiveService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ReceiveService_Update_Handler,
		},
		{
			MethodName: "View",
			Handler:    _ReceiveService_View_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "List",
			Handler:       _ReceiveService_List_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "inventories/receive_service.proto",
}
